import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import StairTransition from "@/components/StairTransition";
import PageTransition from "@/components/PageTransition";
import Footer from "@/components/Footer";
import Head from "next/head";

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"],
weight: ["100","200","300","400","500","600","700","800"],
variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "AK's Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <body className={jetbrainsMono.className}>
        <Header/>
        <StairTransition/>
        <PageTransition>
          {children}
        </PageTransition>
       </body>
    </html>
  );
}
